#!/apps/base/python3/bin/python3

# This is an example plugin that can be used as a
# skeleton for new plugins.
# The documentation string in the plugin class will be used to
# print(the help of the plugin.

from apm.pmanager.abstract import AbsPlugin

global e
global elink

class ReleaseDataPlugin(AbsPlugin):
    """ An example plugin that prints dummy messages """
    def __init__(self):
        pass

    def hook_release_data_command_alter(self, command):
        '''Modify the command in some way (add -e or -link)'''
        global e
        global elink

        s = None
        f = None
        p = command[-1]

        try:
            if '-s' in command:
                s = command[command.index('-s') + 1]
            if '-f' in command:
                f = command[command.index('-f') + 1]
        except:
            return command

        if (s == None or f == None) and s != p and f != p:
            return command

        check = "%s.%s.%s" % (s, f, p)


        new_command = []
        if check in e:
            for i in command:
                new_command.append(i)
                if i == 'release_data':
                    new_command.append('-e')
            command = new_command

        if check in elink:
            for i in command:
                new_command.append(i)
                if i == 'release_data':
                    new_command.append('-link')
                    new_command.append('-e')
            command = new_command

        return command

def load():
    """ Loads the current plugin """
    return ReleaseDataPlugin()


e = [
    "yeu.X1.mmcrmom",
    "acx.M1.hsrluw",
    "ena.C1.csphot",
    "ena.C1.mplpolfs",
    "ena.C1.mwr3c",
    "ena.C1.ceilpblht",
    "ena.C1.sonde",
    "ena.C1.tsi",
    "ena.C1.vdis",
    "ena.C1.mplcmask",
    "ena.C1.qcrad",
    "ena.C1.aod_mfrsr",
    "ena.C1.langley_mfrsr",
    "ena.C1.swfluxanal_skyrad",
    "ena.C1.pblhtsonde",
    "ena.C1.qcrad1long",
    "ena.C1.mfrsrcldod",
    "ena.C1.dlprof_wind",
    "gan.M1.tsi",
    "gan.S1.swacrspec",
    "gan.M1.aod_mfrsr",
    "gan.M1.mplcmask",
    "gan.M1.langley_mfrsr",
    "gan.M1.qcrad1long",
    "grw.M1.mplpol",
    "grw.M1.tsi",
    "grw.M1.wacrspec",
    "grw.M1.mplavg",
    "grw.M1.aod_mfrsr",
    "mag.M1.hsrluw",
    "mao.M1.aeri",
    "mao.M1.ceilpblht",
    "mao.M1.dl",
    "mao.M1.mplpolfs",
    "mao.M1.mwr3c",
    "mao.M1.sashe",
    "mao.M1.sasze",
    "mao.M1.tsi",
    "mao.M1.aip1ogren",
    "mao.M1.aipfitrh1ogren",
    "mao.M1.aerinf",
    "mao.M1.aosccnavg",
    "mao.M1.aosccnavg1jefferson",
    "mao.M1.langley_mfrsr",
    "mao.M1.aod_mfrsr",
    "mao.M1.sasheaod",
    "mao.M1.sashelangley",
    "mao.M1.qcrad",
    "mao.M1.mplcmask",
    "mao.M1.pblhtsonde",
    "mao.M1.pblhtsondeyr",
    "mao.M1.interpolatedsonde",
    "mao.M1.mwrret",
    "mao.M1.dlprof_wind",
    "nsa.C1.aeri",
    "nsa.C1.ceilpblht",
    "nsa.C1.csphot",
    "nsa.C1.hsrluw",
    "nsa.C1.mplpol",
    "nsa.C1.mplpolfs",
    "nsa.C1.sonde",
    "nsa.C1.tsi",
    "nsa.X1.aip1ogren",
    "nsa.X1.aipfitrh1orgen",
    "nsa.C1.aerinf",
    "nsa.C1.gvrpwv",
    "nsa.C1.langley_mfrsr",
    "nsa.C1.langley_nimfr",
    "nsa.C1.aod_mfrsr",
    "nsa.C1.aod_nimfr",
    "nsa.C1.interpolatedsonde",
    "nsa.C1.mergesonde",
    "nsa.C1.mergesonde2",
    "nsa.C1.mplavg",
    "nsa.C1.mplcmask",
    "nsa.C1.pblhtsonde",
    "nsa.C1.pblhtsondeyr",
    "nsa.C1.qcrad",
    "nsa.C1.swfluxanal_skyrad",
    "nsa.C1.surfspecalb",
    "nsa.C2.langley_mfrsr",
    "nsa.C2.langley_nimfr",
    "nsa.C2.aod_mfrsr",
    "nsa.C2.aod_nimfr",
    "nsa.C2.qcrad",
    "nsa.C2.swfluxanal_skyrad",
    "nsa.S01.aeri",
    "nsa.S01.sonde",
    "nsa.S02.sonde",
    "oli.M1.dl",
    "oli.M1.mplpolfs",
    "oli.M1.mwr3c",
    "oli.M1.rl",
    "oli.M1.tsi",
    "oli.M1.ceilpblht",
    "oli.M1.mplcmask",
    "oli.M1.qcrad",
    "oli.M1.aod_mfrsr",
    "oli.M1.langley_mfrsr",
    "oli.M1.swfluxanal_skyrad",
    "oli.M1.pblhtsonde",
    "oli.M1.mfrsrcldod",
    "oli.M1.dlprof_wind",
    "pgh.M1.mplpolfs",
    "pgh.M1.tsi",
    "pgh.M1.wacrspec",
    "pgh.M1.mplavg",
    "pgh.M1.aod_mfrsr",
    "pgh.M1.qcrad1long",
    "pvc.M1.dl",
    "pvc.M1.mplpolfs",
    "pvc.M1.tsi",
    "pvc.M1.mplcmask",
    "pvc.M1.aod_mfrsr",
    "pvc.M1.qcrad1long",
    "sbs.M1.tsi",
    "sbs.S1.swacrspec",
    "sbs.S2.aos",
    "sbs.S2.aoscpc",
    "sbs.S2.aoshumidgr",
    "sbs.S2.aosmaster",
    "sbs.S2.aosmet",
    "sbs.S2.aosozone",
    "sbs.S2.aospsap3w",
    "sgp.F2.mfraaf",
    "sgp.C1.tsi",
    "sgp.C1.ceilpblht",
    "sgp.I6.xsapr",
    "sgp.E14.sebs",
    "sgp.E21.sebs",
    "sgp.C1.sonde",
    "sgp.S01.sonde",
    "sgp.S02.sonde",
    "sgp.S06.sonde",
    "sgp.B1.sonde",
    "sgp.B4.sonde",
    "sgp.B5.sonde",
    "sgp.B6.sonde",
    "sgp.C1.dl",
    "sgp.C1.mplpol",
    "sgp.C1.mplpolfs",
    "sgp.C1.vdis",
    "sgp.X1.iap",
    "sgp.C1.twrmr",
    "sgp.C1.aerinf",
    "sgp.E14.aerinf",
    "sgp.C1.aeriprof3feltz_interp",
    "sgp.C1.aeri01prof3feltz_interp",
    "sgp.C1.aosccnavg1jefferson",
    "sgp.C1.aosccnavg",
    "sgp.C1.beflux",
    "sgp.C1.ccnprof",
    "sgp.C1.dlprof_wind",
    "sgp.C1.lssonde",
    "sgp.C1.sondeadjust",
    "sgp.E12.baebbr",
    "sgp.E13.baebbr",
    "sgp.E15.baebbr",
    "sgp.E19.baebbr",
    "sgp.E20.baebbr",
    "sgp.E4.baebbr",
    "sgp.E7.baebbr",
    "sgp.E9.baebbr",
    "sgp.E32.baebbr",
    "sgp.E34.baebbr",
    "sgp.E35.baebbr",
    "sgp.E36.baebbr",
    "sgp.C1.langley_mfrsr",
    "sgp.E1.langley_mfrsr",
    "sgp.E2.langley_mfrsr",
    "sgp.E3.langley_mfrsr",
    "sgp.E4.langley_mfrsr",
    "sgp.E5.langley_mfrsr",
    "sgp.E6.langley_mfrsr",
    "sgp.E7.langley_mfrsr",
    "sgp.E8.langley_mfrsr",
    "sgp.E9.langley_mfrsr",
    "sgp.E10.langley_mfrsr",
    "sgp.E11.langley_mfrsr",
    "sgp.E12.langley_mfrsr",
    "sgp.E13.langley_mfrsr",
    "sgp.E15.langley_mfrsr",
    "sgp.E16.langley_mfrsr",
    "sgp.E18.langley_mfrsr",
    "sgp.E19.langley_mfrsr",
    "sgp.E20.langley_mfrsr",
    "sgp.E22.langley_mfrsr",
    "sgp.E24.langley_mfrsr",
    "sgp.E27.langley_mfrsr",
    "sgp.E31.langley_mfrsr",
    "sgp.E32.langley_mfrsr",
    "sgp.E33.langley_mfrsr",
    "sgp.E34.langley_mfrsr",
    "sgp.E35.langley_mfrsr",
    "sgp.E36.langley_mfrsr",
    "sgp.E37.langley_mfrsr",
    "sgp.E38.langley_mfrsr",
    "sgp.C1.langley_nimfr",
    "sgp.C1.aod_mfrsr",
    "sgp.E1.aod_mfrsr",
    "sgp.E2.aod_mfrsr",
    "sgp.E3.aod_mfrsr",
    "sgp.E4.aod_mfrsr",
    "sgp.E5.aod_mfrsr",
    "sgp.E6.aod_mfrsr",
    "sgp.E7.aod_mfrsr",
    "sgp.E8.aod_mfrsr",
    "sgp.E9.aod_mfrsr",
    "sgp.E10.aod_mfrsr",
    "sgp.E11.aod_mfrsr",
    "sgp.E12.aod_mfrsr",
    "sgp.E13.aod_mfrsr",
    "sgp.E15.aod_mfrsr",
    "sgp.E16.aod_mfrsr",
    "sgp.E18.aod_mfrsr",
    "sgp.E19.aod_mfrsr",
    "sgp.E20.aod_mfrsr",
    "sgp.E22.aod_mfrsr",
    "sgp.E24.aod_mfrsr",
    "sgp.E27.aod_mfrsr",
    "sgp.E31.aod_mfrsr",
    "sgp.E32.aod_mfrsr",
    "sgp.E33.aod_mfrsr",
    "sgp.E34.aod_mfrsr",
    "sgp.E35.aod_mfrsr",
    "sgp.E36.aod_mfrsr",
    "sgp.E37.aod_mfrsr",
    "sgp.E38.aod_mfrsr",
    "sgp.C1.aod_nimfr",
    "sgp.C1.aip1ogren",
    "sgp.C1.aipfitrh1ogren",
    "sgp.C1.aerosolbe",
    "sgp.C1.interpolatedsonde",
    "sgp.C1.mfrsrcldod",
    "sgp.E9.mfrsrcldod",
    "sgp.E11.mfrsrcldod",
    "sgp.E12.mfrsrcldod",
    "sgp.E13.mfrsrcldod",
    "sgp.E15.mfrsrcldod",
    "sgp.E21.mfrsrcldod",
    "sgp.E31.mfrsrcldod",
    "sgp.E32.mfrsrcldod",
    "sgp.E33.mfrsrcldod",
    "sgp.E34.mfrsrcldod",
    "sgp.E35.mfrsrcldod",
    "sgp.E36.mfrsrcldod",
    "sgp.E37.mfrsrcldod",
    "sgp.E38.mfrsrcldod",
    "sgp.C1.kazrspec",
    "sgp.C1.mmcrspec",
    "sgp.C1.mplavg",
    "sgp.C1.mplcmask",
    "sgp.C1.pblhtsonde",
    "sgp.C1.pblhtsondeyr",
    "sgp.C1.qcrad",
    "sgp.E1.qcrad",
    "sgp.E2.qcrad",
    "sgp.E3.qcrad",
    "sgp.E4.qcrad",
    "sgp.E5.qcrad",
    "sgp.E6.qcrad",
    "sgp.E7.qcrad",
    "sgp.E8.qcrad",
    "sgp.E9.qcrad",
    "sgp.E10.qcrad",
    "sgp.E11.qcrad",
    "sgp.E12.qcrad",
    "sgp.E13.qcrad",
    "sgp.E15.qcrad",
    "sgp.E16.qcrad",
    "sgp.E18.qcrad",
    "sgp.E19.qcrad",
    "sgp.E20.qcrad",
    "sgp.E21.qcrad",
    "sgp.E22.qcrad",
    "sgp.E24.qcrad",
    "sgp.E27.qcrad",
    "sgp.E31.qcrad",
    "sgp.E32.qcrad",
    "sgp.E33.qcrad",
    "sgp.E34.qcrad",
    "sgp.E35.qcrad",
    "sgp.E36.qcrad",
    "sgp.E37.qcrad",
    "sgp.E38.qcrad",
    "sgp.C1.qcrad_beflux",
    "sgp.C1.qcrad_brs",
    "sgp.C1.rlprof_merge",
    "sgp.C1.sasheaod",
    "sgp.C1.sashelangley",
    "sgp.C1.surfspecalb",
    "sgp.C1.swfluxanal_brs",
    "sgp.C1.swfluxanal_sirs",
    "sgp.E1.swfluxanal_sirs",
    "sgp.E2.swfluxanal_sirs",
    "sgp.E3.swfluxanal_sirs",
    "sgp.E4.swfluxanal_sirs",
    "sgp.E5.swfluxanal_sirs",
    "sgp.E6.swfluxanal_sirs",
    "sgp.E7.swfluxanal_sirs",
    "sgp.E8.swfluxanal_sirs",
    "sgp.E9.swfluxanal_sirs",
    "sgp.E10.swfluxanal_sirs",
    "sgp.E11.swfluxanal_sirs",
    "sgp.E12.swfluxanal_sirs",
    "sgp.E13.swfluxanal_sirs",
    "sgp.E15.swfluxanal_sirs",
    "sgp.E16.swfluxanal_sirs",
    "sgp.E18.swfluxanal_sirs",
    "sgp.E19.swfluxanal_sirs",
    "sgp.E20.swfluxanal_sirs",
    "sgp.E21.swfluxanal_sirs",
    "sgp.E22.swfluxanal_sirs",
    "sgp.E24.swfluxanal_sirs",
    "sgp.E25.swfluxanal_sirs",
    "sgp.E27.swfluxanal_sirs",
    "sgp.E31.swfluxanal_sirs",
    "sgp.E32.swfluxanal_sirs",
    "sgp.E33.swfluxanal_sirs",
    "sgp.E34.swfluxanal_sirs",
    "sgp.E35.swfluxanal_sirs",
    "sgp.E36.swfluxanal_sirs",
    "sgp.E37.swfluxanal_sirs",
    "sgp.E38.swfluxanal_sirs",
    "tmp.M1.aeri",
    "tmp.M1.assist",
    "tmp.M1.hsrluw",
    "tmp.M1.langley_mfrsr",
    "tmp.M1.aod_mfrsr",
    "tmp.M1.qcrad",
    "tmp.M1.mplcmask",
    "tmp.M1.pblhtsonde",
    "tmp.M1.pblhtsondeyr",
    "tmp.M1.interpolatedsonde",
    "tmp.M1.mwrret",
    "tmp.M1.mfrsrcldod",
    "twp.C1.aeri",
    "twp.C1.csphot",
    "twp.C1.kazrspec",
    "twp.C1.mplpol",
    "twp.C1.mplpolfs",
    "twp.C1.sonde",
    "twp.C1.tsi",
    "twp.C2.csphot",
    "twp.C2.sonde",
    "twp.C2.tsi",
    "twp.C3.aeri",
    "twp.C3.csphot",
    "twp.C3.dl",
    "twp.C3.kazrspec",
    "twp.C3.mplpol",
    "twp.C3.mplpolfs",
    "twp.C3.sonde",
    "twp.C3.mmcrspec",
    "twp.C3.tsi",
    "twp.I10.csapr",
    "twp.C1.aerinf",
    "twp.C3.aerinf",
    "twp.C1.langley_mfrsr",
    "twp.C2.langley_mfrsr",
    "twp.C3.langley_mfrsr",
    "twp.C1.aod_mfrsr",
    "twp.C2.aod_mfrsr",
    "twp.C3.aod_mfrsr",
    "twp.C1.mplavg",
    "twp.C1.mplavg",
    "twp.C3.mplavg",
    "twp.C1.mplcmask",
    "twp.C3.mplcmask",
    "twp.C1.pblhtsonde",
    "twp.C2.pblhtsonde",
    "twp.C3.pblhtsonde",
    "twp.C1.sondeadjust",
    "twp.C2.sondeadjust",
    "twp.C3.sondeadjust",
    "twp.C1.qcrad",
    "twp.C2.qcrad",
    "twp.C3.qcrad",
    "twp.C1.swfluxanal_skyrad",
    "twp.C2.swfluxanal_skyrad",
    "twp.X1.avhrrdar",
    "twp.C3.rlprof_merge"
]

elink = [
    "ena.C1.kasacr",
    "ena.C1.kazr",
    "ena.C1.wsacr",
    "mao.M1.kasacr",
    "mao.M1.kasacrspec",
    "mao.M1.wacr",
    "mao.M1.wacrspec",
    "mao.M1.wsacr",
    "mao.M1.wsacrspec",
    "oli.M1.kasacr",
    "oli.M1.kazr",
    "oli.M1.wsacr",
    "pvc.M1.kasacr",
    "pvc.M1.kasacrspec",
    "pvc.M1.wacr",
    "pvc.M1.wacrspec",
    "pvc.M1.wsacr",
    "pvc.M1.wsacrspec",
    "sgp.C1.irsi",
    "sgp.C1.kasacr",
    "sgp.C1.kasacrspec",
    "sgp.C1.wsacr",
    "sgp.C1.wsacrspec",
    "tmp.M1.kasacrspec",
    "tmp.M1.xsacrspec",
    "twp.C3.kasacr",
    "twp.C3.kasacrspec",
    "twp.C3.xsacr",
    "twp.C3.xsacrspec",
    "nsa.C1.kasacr",
    "nsa.C1.kasacrspec",
    "nsa.C1.wsacr",
    "nsa.C1.wsacrspec",
    "twp.C1.kasacr",
    "twp.C1.kasacrspec",
    "twp.C1.xsacr",
    "twp.C1.xsacrspec"
]
