# Generic configuration
# ---------------------

# Config for current application
# ------------------------------

nc2csv:
  foo: bar
  bar: [1, 2]

# Config for logging
# ------------------
# From https://gist.github.com/glenfant/4358668
# See http://docs.python.org/2.7/library/logging.config.html#configuration-dictionary-schema

logging:
  version: 1
  disable_existing_loggers: False

  loggers:
    nc2csv_logger:
      handlers: [console, debug_file_handler]
      qualname: nc2csv_logger
      propagate: false
    nc2csv_test_logger:
      handlers: [test_console]
      qualname: nc2csv_test_logger
      propagate: false
    reproc_logger:
      handlers: [console, debug_file_handler]
      qualname: nc2csv_logger
      propagate: false
    reproc_test_logger:
      handlers: [test_console]
      qualname: nc2csv_test_logger
      propagate: false

  formatters:
      simple:
          format: "%(levelname)s — %(funcName)s:%(lineno)d — %(message)s"
      lineInfo:
          format: "%(asctime)s — %(name)s — %(levelname)s — %(funcName)s:%(lineno)d — %(message)s"

  handlers:
      console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout
      test_console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
      debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: lineInfo
        filename: logs/debug.log
        maxBytes: 10485760 # 10MB
        backupCount: 10
        encoding: utf8
      info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: logs/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 10
        encoding: utf8
      error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: logs/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 10
        encoding: utf8
  root:
    level: DEBUG
    handlers: [console, info_file_handler, error_file_handler, debug_file_handler]
